#!/bin/bash

############# FOR EACH ####################

for process in $(ps ax | grep bash | awk '{print $1}')
do 
	echo "Awk RESULT: $process"
done

var="awk sed print"
for i in $(echo $var | sed "s/ /\n/g")
do 
echo "FOR EACH RESULT: $i"
done


####### AWK ############

#AWK Ignore first line
ps aux | awk 'NR==1{next}{print $4}'


############### FOR ######################

for(( i=0; i<10; i++ ))
do 
	echo $i
done 


#############  CASE ###############

case $1 in
	1) echo "op 1" ;;
	2) echo "op 2" ;;
	*) echo "Inválid" ;;

esac


######### CUT ######################

i="2.5"
echo $i | cut -d '.' -f1
echo $i | cut -d '.' -f2
echo $i | sed 's/\..*//g'
echo $i | sed 's/\.[0-9]*//g'


######### FIND #################
find / -type f -name '*.cpp'
find / -type d -iname 'virtuoso' 2>/dev/null


###### KILL ##########

ps ax | grep java | awk '{print $1}' | xargs kill -9
